services:
  api:
    image: slowback1/wheel-of-slowback-backend:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.wheel.slowback.net`)"
      - "traefik.http.services.api.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.entrypoints=web"
    ports:
      - "8081:8080"
    volumes:
      - ./appsettings.json:/appsettings.Release.json
      - ./data:/data
  frontend:
    image: slowback1/wheel-of-slowback-frontend:latest
    volumes:
      - ./frontend-config.json:/usr/share/nginx/html/config/config.json
    ports:
      - "80:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`www.wheel.slowback.net`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.entrypoints=web"